### ISSUE TITLE
ToDo list for the governance repo

### ISSUE THREAD

**Issue by ocefpaf** [ioos/governance#3]
- [ ] policy/recommendations for licenses
- [ ] code review best practices
- [ ] PR best practices
- [ ] CI configuration
- [X] pre-commit use

**Comment by MathewBiddle** [comment]
- [ ] dependabot

**Comment by MathewBiddle** [comment]
- [ ] adding people to teams or creating a new team

**Comment by MathewBiddle** [comment]
paraphrase from @mwengren on GitHub teams:

> we try to use GitHub Teams as much as possible, because they allow someone who isn't an Org admin, to manage membership of the team.  
> 
> So a maintainer can add/remove people from the team.  The catch is that they must first be members of the IOOS Org in order to be added.  Once they are members, then they can be added/removed from teams as necessary.

**Comment by MathewBiddle** [comment]
Add guidance for new repositories/projects. I've been pointing people to https://opensource.guide/starting-a-project/#launching-your-own-open-source-project

**Comment by ocefpaf** [comment]
This one would be 1 level down the one you posted above but has some good guides on packaging, etc: https://learn.scientific-python.org/development/
